### ISSUE TITLE
How to read CIFAR images with scala in mmlspark

### ISSUE THREAD

**Issue by Myasuka** [Azure/mmlspark#63] opened 2017-07-07 06:43 UTC
Currently, [example 301](https://github.com/Azure/mmlspark/blob/master/notebooks/samples/301%20-%20CIFAR10%20CNTK%20CNN%20Evaluation.ipynb) which evaluates pre-trained CNTK model with CIFAR10 images, is totally written by python. This example use `pickle.load` to read `cifar-10-batches-py/test_batch` and then parallelize to distributed RDD, however, I cannot directly use `pickle` to read data in scala code application. 

I tried `spark.readImages` in mmlspark, but it seems cannot deal with `cifar-10-batches-bin` data well. And I finally choose [cookie-datasets](https://github.com/cookieai/cookie-datasets) to read cifar data in scala (the master branch of cookie-datasets still used spark-1.5, and I upgrade it to spark-2.1 with necessary [changes](https://github.com/cookieai/cookie-datasets/pull/7))

BTW, since you only have python examples, and I have already interpreted 101 and part 301 examples code to scala, I'm not sure whether you want this part of example codes?

**Comment by drdarshan** [comment] 2017-07-07 14:50
Dear Myasuka,
1. For reading CIFAR-10 in Scala, we have a version of the dataset in a zip file hosted on our CDN.  I will send you an example as soon as I have verified that it works. 
1. We would love to have your Scala examples! Could you please let us know how you have them implemented? Is it as a standalone application or does it use the Jupyter Scala kernel? If you could please send us a pointer, we will be happy to work with you to integrate them.

Thank you so much.

**Comment by drdarshan** [comment] 2017-07-07 22:53
Dear Myasuka,
You can get a zip version of the CIFAR test dataset here: https://mmlspark.azureedge.net/datasets/CIFAR10/test.zip. 

Once you copy the zip file to HDFS (or local file system), I just confirmed, you can do something like this in Scala:

```scala
import com.microsoft.ml.spark.Readers.implicits._
val images = spark.readImages("file:///home/mmlspark/test.zip", true, 1.0, true)

images.printSchema()

/* This produces
root
 |-- image: struct (nullable = true)
 |    |-- path: string (nullable = true)
 |    |-- height: integer (nullable = true)
 |    |-- width: integer (nullable = true)
 |    |-- type: integer (nullable = true)
 |    |-- bytes: binary (nullable = true)
*/

images.selectExpr("image.width as w", "image.height as h", "image.bytes as b").show()

/* This produces:
+---+---+--------------------+
|  w|  h|                   b|
+---+---+--------------------+
| 32| 32|[5B 65 6D 62 68 6...|
| 32| 32|[01 01 01 01 01 0...|
| 32| 32|[F8 F8 F8 F6 F6 F...|
| 32| 32|[99 98 94 5E 5C 5...|
| 32| 32|[DC DF D7 C5 CE B...|
| 32| 32|[B0 D5 F3 AE D3 F...|
| 32| 32|[6B 38 22 67 36 2...|
| 32| 32|[4C 69 64 53 65 6...|
| 32| 32|[DC A1 70 DC A1 7...|
| 32| 32|[BB CE DF BA CD D...|
| 32| 32|[22 27 29 1D 21 2...|
| 32| 32|[F5 FE FD AE BC B...|
| 32| 32|[C5 BA AA C9 BC A...|
| 32| 32|[95 77 84 95 78 8...|
| 32| 32|[91 B5 C1 93 AC B...|
| 32| 32|[7C 8C A7 72 8B A...|
| 32| 32|[31 39 4E 44 4A 6...|
| 32| 32|[34 3A 3C 28 2E 2...|
| 32| 32|[DA CF CB D9 CD C...|
| 32| 32|[27 AB 9C 25 B1 9...|
+---+---+--------------------+
only showing top 20 rows
*/
```

Please let me know if this helps. Thank you!

**Comment by Myasuka** [comment] 2017-07-10 02:40
@drdarshan , thanks for your help.
From your reply, MMLSpark seems can only support to read images instead of original CIFAR binary format from [official site](http://www.cs.toronto.edu/~kriz/cifar.html) with scala, did I misunderstand? That's to say, if we download original binary format file, we need to first transform them into images one by one?

**Comment by drdarshan** [comment] 2017-07-11 16:13
Hello @Myasuka, yes, you would need to transform the images. I might be able to write a UDF to do this from Scala since looks like they have a binary format in addition to pickle and MAT. Please let me know if that would help and I can write one for you. Thanks!

**Comment by Myasuka** [comment] 2017-07-12 04:20
Really thanks for your kindness help, I already use [my modified cookie-datasets](https://github.com/Myasuka/cookie-datasets) to read original CIFAR10 binary format data.

BTW, I think you can also share the transform script since there maybe someone else want to try MMLSpark with scala but found hard to read original CIFAR10 binary format data without your provided https://mmlspark.azureedge.net/datasets/CIFAR10/test.zip

**Comment by drdarshan** [comment] 2017-07-12 19:49
Hello @Myasuka, here is a simple Python3 script that extracts the images from the original CIFAR Python dataset and writes them out as PNG images. You can then zip the directory and use ``spark.readImages`` to read it. Please let me know if this is sufficient.

Thank you!
Sudarshan

```py
import os
import tarfile, pickle
import PIL
with tarfile.open("cifar-10-python.tar.gz", "r:gz") as f:
    for batch in [p for p in f.getnames() if "_batch" in p]:
        print("Extracting: "+batch)
        os.makedirs(batch, exist_ok=True)
        images = pickle.load(f.extractfile(batch), encoding="latin1")
        data, filenames = images["data"], images["filenames"]
        for img_data, filename in zip(data, filenames):
            img = PIL.Image.fromarray(img_data.reshape(3,32,32).transpose(1,2,0))
            img.save(os.path.join(batch, filename))
```

**Comment by drdarshan** [comment] 2017-07-25 18:42
Hi @Myasuka, I'm closing this issue for now.. please reopen if you are still blocked. Thank you!

**Closed by drdarshan** 2017-07-25 18:42 UTC

**Comment by alg-jmx** [comment] 2017-10-16 04:19
why mmlspark hasn't more example using scala? I'm more interesting in scala with spark in mmlspark~
