### ISSUE TITLE
LGBMRanker class not present

### ISSUE THREAD

**Issue by gulshan-gaurav** [Azure/mmlspark#446] opened 2018-11-29 09:03 UTC

**Comment by imatiach-msft** [comment] 2018-12-27 17:53
@gulshan-gaurav thank you for the feedback - since there currently doesn't exist a ranker in Spark ML, could you give some more details on how you think the API should look like?  I've wanted to add this as well but would like to get some feedback from the community in regards to how the API should look like.  I'm also not sure what base class I should use from Spark ML or if I should create my own - for example, for LightGBMClassifier we use ProbabilisticClassifier:

https://github.com/apache/spark/blob/v2.4.0/mllib/src/main/scala/org/apache/spark/ml/classification/ProbabilisticClassifier.scala#L53

And for regression I use Regressor:

https://github.com/apache/spark/blob/v2.4.0/mllib/src/main/scala/org/apache/spark/ml/regression/Regressor.scala#L31

**Comment by ykicisk** [comment] 2019-02-11 06:17
@imatiach-msft 

Hi, I suggest the API should be like "Regressor with [group_column](https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.rst#group_column)" .

In particular, 
1. implement trait `HasGroupCol` like [HasFeaturesCol](https://github.com/apache/spark/blob/v2.4.0/mllib/src/main/scala/org/apache/spark/ml/param/shared/sharedParams.scala#L66)
2. implement trait `RankerParams` with `HasGroupCol` like [PredictorParams](https://github.com/apache/spark/blob/v2.4.0/mllib/src/main/scala/org/apache/spark/ml/Predictor.scala#L34-L35)
3. implement abstract class `Ranker` with `RankerParams` like [Regressor](https://github.com/apache/spark/blob/v2.4.0/mllib/src/main/scala/org/apache/spark/ml/regression/Regressor.scala#L31)

**Comment by imatiach-msft** [comment] 2019-06-04 03:46
closing as LightGBMRanker has been added with the suggested API

**Closed by imatiach-msft** 2019-06-04 03:46 UTC
Labels: LightGBM, enhancement, high priority
