### ISSUE TITLE
LightGBM, job running for a very long time, "reduce at LightGBMClassifier.scala:85"

### ISSUE THREAD

**Issue by sunilsu** [Azure/mmlspark#542] opened 2019-04-17 21:09 UTC
I have a dataset in parquet with 3M+ rows and 2600+ columns. I am trying to train a LightGBMClassifier on EMR cluster. My spark config is "--driver-memory 64g --executor-memory 64g --executor-cores 5 --num-executors 18". 

The job "reduce at LightGBMClassifier.scala:85" has been running for ~ 4hours and hasn't finished yet.

When I convert the parquet to libsvm format and rerun the training, it completes 100 iterations in about 8 minutes (~4 seconds per iter). But converting parquet to libsvm takes ~ 3 hours too.

I am wondering if there is anything I need to change with this configuration (#executor-cores, #executor-instances, #executor-memory) to speed up this step? 

Also, the number of partitions created when I read the data is much more than what LightGBMClassifier wants to repartition to. In this case LightGBM is repartitioning to 90 (18 * 5), but the data I read has 579 partitions.

<img width="318" alt="Screen Shot 2019-04-17 at 4 07 07 PM" src="https://user-images.githubusercontent.com/2791700/56320954-f8129980-612a-11e9-8949-1def18c191ca.png">
<img width="1649" alt="Screen Shot 2019-04-17 at 4 06 32 PM" src="https://user-images.githubusercontent.com/2791700/56320979-082a7900-612b-11e9-910f-86cf7d97b315.png">

**Comment by imatiach-msft** [comment] 2019-04-18 03:20
hi @sunilsu , sorry about the issues you are having.  I have a couple suggestions:
1.) 
Could you try to use voting parallel instead of data parallel?  Please see here for more info:
https://github.com/Microsoft/LightGBM/blob/master/docs/Parallel-Learning-Guide.rst
Please see parallelism parameter:
https://github.com/Azure/mmlspark/blob/master/src/lightgbm/src/main/scala/LightGBMParams.scala#L13

2.)
This is very unexpected for me:
```
When I convert the parquet to libsvm format and rerun the training, it completes 100 iterations in about 8 minutes (~4 seconds per iter)
```
Do you have mostly sparse data?  Maybe the parquet is storing the vector in dense instead of sparse format?  This is probably unlikely but I'm not sure why libsvm would be so much faster.

3.)
Could you try the latest build instead of the official build (there is at least one for each pull request):
--packages 
com.microsoft.ml.spark:mmlspark_2.11:0.16.dev15+2.g2d494cb
and --repositories 
https://mmlspark.azureedge.net/maven
@eisber has added some significant optimizations to lightgbm, specifically for dense + sparse scoring case and sparse training case.

4.)
Could you please post the code especially parameters you are running?

**Comment by sunilsu** [comment] 2019-04-18 19:55
Thanks for your reply @imatiach-msft 

1. I reran the code with the latest build ( com.microsoft.ml.spark:mmlspark_2.11:0.16.dev15+2.g2d494cb ) and tried both **data_parallel** and **voting_parallel** for parallelism. There was no difference, the job `reduce at LightGBMBase.scala:51
 ` is stuck or is very slow. The SQL tab of Spark UI shows the following,

<img width="264" alt="Screen Shot 2019-04-18 at 2 41 57 PM" src="https://user-images.githubusercontent.com/2791700/56386961-bfd19080-61e8-11e9-80ae-4f78874fe741.png">

Its stuck in InMemoryTableScan. There are 3M+ rows and currently it says 530K rows. Its the same behaviour with 0.16. 

2. My code is very basic. I am using most of the default params, just to get one pass with the code working before making changes to it. Here is part of code I used for parquet files,

```
df = spark.read.parquet(*hdfs_paths)
train, test = df.randomSplit([0.85, 0.15], seed=1)
lgbm = LightGBMClassifier(learningRate=0.1, numIterations=1000, parallelism='voting_parallel')
model = TrainClassifier(model=lgbm, labelCol="label", numFeatures=256).fit(train)
```

**Comment by imatiach-msft** [comment] 2019-04-18 21:05
@sunilsu sorry, I was really hoping voting parallel would make a big difference, too bad it does not.  TrainClassifier does a lot of featurization under the hood that may not make sense by default for the data you have.  Could you try doing a custom featurization and then passing the vector column directly to LightGBMClassifier?  The LightGBMClassifier has the same interface as all of the other Spark ML classifiers.  What does the schema of your data look like?  If you have categorical columns, LightGBM can handle them directly and you won't need to one-hot-encode them, just index them.
I'm still not quite sure why your processing is so slow, although I have a feeling it might be due to the large number of columns.  Are they all numeric?
Also, if there is some way we could talk over skype or teams that might make debugging faster.

**Comment by sunilsu** [comment] 2019-04-18 23:19
@imatiach-msft 
My dataset is 99% numeric columns, only 2 categorical. I dropped categorical columns, used VectorAssembler to pack features and called LightGBMClassifier. (Did not use TrainClassifier). I see the same behaviour, stuck at reduce job. The SQL tab looks different though, its below

<img width="331" alt="Screen Shot 2019-04-18 at 6 15 08 PM" src="https://user-images.githubusercontent.com/2791700/56396766-01246900-6206-11e9-947d-e0b6279ca031.png">

Let me check how to communicate outside the company and get back to you, definitely appreciate your help in debugging this! Thanks!

**Comment by eisber** [comment] 2019-04-19 07:17
The model sounds a bit bigger. @imatiach-msft remember the the map optimization we worked on to only return a model from a single partition? I'll try to get around to it next week.

**Comment by sunilsu** [comment] 2019-04-22 19:13
Thanks @imatiach-msft for looking into it.

Some of the partitions did not have both the classes in it. When that happens, some of the workers exit causing this issue. The workaround now is the randomly shuffle the dataset before calling train and this should hopefully spread both classes among all partitions.

For multi-class case, is it required that all partitions have data for all classes?

**Comment by tyler-romero** [comment] 2019-05-10 17:23
@imatiach-msft I was encountering this too. It would be nice if a warning was logged in this case.

**Comment by imatiach-msft** [comment] 2019-05-10 17:59
@tyler-romero @sunilsu yes, I just discussed this with @eisber - the solution will be to fail with a nice error message and then provide an additional stratified splitter across partitions that the user can explicitly call before lightgbm.  That way, we won't force the user to wait until timeout, the user will know what the issue is, we can provide a solution for them - all while not hurting lightgbm performance benchmarks (which would be the case if we tried to do the stratified splitting within lightgbm)

**Comment by imatiach-msft** [comment] 2019-10-09 03:30
this issue is now fixed in latest master with the upgrade to lightgbm 2.3.1
https://github.com/Azure/mmlspark/pull/705
lightgbm can now handle missing binary and multiclass labels in the distributed case and shouldn't get stuck

**Closed by imatiach-msft** 2019-10-09 03:30 UTC

**Comment by allardAmwayDS** [comment] 2019-10-24 20:04
@imatiach-msft 
What version of mmlspark would contain this fix?

e.g. which is the latest:
pyspark --packages com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1

**Comment by rusonding** [comment] 2020-10-20 02:52
> this issue is now fixed in latest master with the upgrade to lightgbm 2.3.1
> #705
> lightgbm can now handle missing binary and multiclass labels in the distributed case and shouldn't get stuck

--------------- ------------
num-executors=1 faster then num-executors=20; running 1min when num-executors=1 and partition=1 , but running 1hour when num-executors=10 and partition=10, what happen?

spark2-submit --master yarn --jars file:///root/.ivy2/jars/com.microsoft.ml.spark_mmlspark_2.11-1.0.0-rc1.jar,file:///root/.ivy2/jars/com.microsoft.ml.lightgbm_lightgbmlib-2.3.100.jar --packages com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1 --conf spark.pyspark.python=/usr/lib/anaconda2/envs/mmlspark/bin/python --num-executors 20 --executor-memory 10G test_mmlspark2.py


``` 
certifi         2016.2.28
future          0.18.2
joblib          0.17.0
lightgbm        3.0.0
mmlspark        0.0.11111111
numpy           1.19.2
pip             20.2.3
py4j            0.10.7
PyHive          0.6.1
pyspark         2.4.5
python-dateutil 2.8.1
scikit-learn    0.23.2
scipy           1.5.3
setuptools      36.4.0
six             1.15.0
threadpoolctl   2.1.0
wheel           0.29.0
```

**Comment by toughrogrammer** [comment] 2021-05-13 11:58
using `com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc3` but there is same problem. 
lightgbm version is `com.microsoft.ml.lightgbm_lightgbmlib-2.3.180`

**Comment by toughrogrammer** [comment] 2021-05-13 12:58
I tried num executor 1 and it makes model fitting really fast. 
It looks like LightGBM has issue about distributed node model fitting.
