### ISSUE TITLE
LightGBM: ComputeModelStatistics evaluationMetrics='all' fails with java.lang.Exception: Please score the model prior to evaluating

### ISSUE THREAD

**Issue by sunilsu** [Azure/mmlspark#557] opened 2019-04-30 03:41 UTC
**evaluationMetric = 'AUC'** works fine. So does **precision**, **recall** and **accuracy**
But 'all' fails.
```
metrics = ComputeModelStatistics(evaluationMetric='all',
                                 labelCol='label',
                                 scoresCol='rawPrediction',
                                 scoredLabelsCol='prediction') \
            .transform(scoredData)
```
throws the following error,
```
Py4JJavaError: An error occurred while calling o3815.transform.
: java.lang.Exception: Please score the model prior to evaluating
	at com.microsoft.ml.spark.metrics.MetricUtils$.getSchemaInfo(MetricUtils.scala:27)
```

**Comment by imatiach-msft** [comment] 2019-05-01 04:27
@sunilsu sorry, since you are not using TrainClassifier or TrainRegressor but instead the generic spark ML api you need to explicitly specify whether this is for classification or regression in the evaluation metric instead of "all", otherwise there is no way to know since there is no metadata anywhere (which the TrainClassifier or TrainRegressor add to the dataset):
"classification"
"regression"

**Comment by imatiach-msft** [comment] 2019-05-01 04:34
@sunilsu I've sent a PR here to fix this issue:
https://github.com/Azure/mmlspark/pull/558
FYI you can also use the evaluators from Spark ML with LightGBM (eg https://spark.apache.org/docs/latest/api/java/index.html?org/apache/spark/ml/evaluation/BinaryClassificationEvaluator.html or https://spark.apache.org/docs/latest/api/java/index.html?org/apache/spark/ml/evaluation/RegressionEvaluator.html).  LightGBM can be used with any of the Spark ML estimators/transformers that accept a prediction model, since it uses the same base class as all of the other learners in Spark ML.
Having said that ComputeModelStatistics is optimized for computing multiple metrics and should be faster than the Spark ML evaluators - besides having a better API (transformer) that fits into the spark ecosystem.

**Comment by imatiach-msft** [comment] 2019-05-01 16:14
closing as PR with better error message has been merged to master and should be in next release

**Closed by imatiach-msft** 2019-05-01 16:14 UTC

**Comment by ttpro1995** [comment] 2019-11-13 04:03
how to " explicitly specify whether this is for classification or regression in the evaluation metric" ? 

Please give code example.
